### ISSUE TITLE
Support for new BackEnd system

### ISSUE THREAD

**Issue by Damounet** [microcks/microcks-backstage-provider#22]
### Reason/Context

As of 1.24, backstage promotes the new back end system as the default backend in the backstage create app cli command.

The Microcks plugin does not support it yet natively.

### Description

Provide a BackendModule that enables the activation of the Microcks plugin in the form of :

```javascript
backend.add(import('@microcks/microcks-backstage-backend'));
```
in packages/backend/src/index.ts

### Implementation ideas

I have started to work on this plugin, to use as an internal plugin but it does not work yet.

I have created the microcksProvider.ts file with
```javascript
import {coreServices, createBackendModule} from "@backstage/backend-plugin-api";
import {MicrocksApiEntityProvider} from "@microcks/microcks-backstage-provider";
import { catalogProcessingExtensionPoint } from '@backstage/plugin-catalog-node/alpha';
import {loggerToWinstonLogger} from "@backstage/backend-common";

export default createBackendModule({
  pluginId: 'microcks',
  moduleId: 'microcksProvider',
  register(reg) {
    reg.registerInit({
      deps: {
        catalog: catalogProcessingExtensionPoint,
        config: coreServices.rootConfig,
        logger: coreServices.logger,
        scheduler: coreServices.scheduler,
      },
      async init({ catalog, config, logger, scheduler }) {
        catalog.addEntityProvider(
          MicrocksApiEntityProvider.fromConfig(config, {
            logger: loggerToWinstonLogger(logger),
            scheduler: scheduler,
            schedule: scheduler.createScheduledTaskRunner({
              frequency: { minutes: 2 },
              timeout: { minutes: 1 },
            }),
          })
        )
      },
    });
  },
});
```
I got inspired by the alpha file done for red hat https://github.com/microcks/microcks-backstage-provider/blob/main/src/dynamic/alpha.ts

And included the module in the index.ts like so:

```javascript
backend.add(import('./plugins/microcksProvider'));
```

It compiles but fails to start properly...
```bash
[1] /mnt/c/work/ASD/backstage/node_modules/@backstage/backend-app-api/src/wiring/BackendInitializer.ts:67
[1]           throw new Error(
[1]                 ^
[1] Error: Illegal dependency: Module 'microcksProvider' for plugin 'microcks' attempted to depend on extension point 'catalog.processing' for plugin 'catalog'. Extension points can only be used within their plugin's scope.     
[1]     at BackendInitializer.getInitDeps_fn (/mnt/c/work/ASD/backstage/node_modules/@backstage/backend-app-api/src/wiring/BackendInitializer.ts:67:17)
[1]     at <anonymous> (/mnt/c/work/ASD/backstage/node_modules/@backstage/backend-app-api/src/wiring/BackendInitializer.ts:261:40)
[1]     at processNode (/mnt/c/work/ASD/backstage/node_modules/@backstage/backend-app-api/src/lib/DependencyGraph.ts:234:28)
[1]     at Array.map (<anonymous>)
[1]     at processMoreNodes (/mnt/c/work/ASD/backstage/node_modules/@backstage/backend-app-api/src/lib/DependencyGraph.ts:226:40)
[1]     at _DependencyGraph.parallelTopologicalTraversal (/mnt/c/work/ASD/backstage/node_modules/@backstage/backend-app-api/src/lib/DependencyGraph.ts:242:11)
[1]     at <anonymous> (/mnt/c/work/ASD/backstage/node_modules/@backstage/backend-app-api/src/wiring/BackendInitializer.ts:259:22)
[1]     at Array.map (<anonymous>)
[1]     at BackendInitializer.doStart_fn (/mnt/c/work/ASD/backstage/node_modules/@backstage/backend-app-api/src/wiring/BackendInitializer.ts:237:20)
[1]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[1]     at BackendInitializer.start (/mnt/c/work/ASD/backstage/node_modules/@backstage/backend-app-api/src/wiring/BackendInitializer.ts:149:5)
[1]     at BackstageBackend.start (/mnt/c/work/ASD/backstage/node_modules/@backstage/backend-app-api/src/wiring/BackstageBackend.ts:42:11)
[1]
[1] Node.js v20.9.0
```

**Comment by lbroudoux** [comment]
Adding a new `module.ts` file that is exporting Microcks provider as a new Backend system module
