### ISSUE TITLE
plugin does not work for backend version 1.0 since backstage 1.31

### ISSUE THREAD

**Issue by Damounet** [microcks/microcks-backstage-provider#57]
### Describe the bug

Having the plugin enabled and configured works on 1.29,  I updated backstage to 1.32, and when starting the app it ends with this logs :

[1] /mnt/c/work/ASD/backstage-asd/node_modules/@backstage/backend-defaults/node_modules/@backstage/backend-app-api/src/wiring/BackendInitializer.ts:547
[1]     throw new Error(`Invalid BackendFeature, bad type '${feature.$$type}'`);
[1]           ^
[1] 
[1] 
[1] Error: Invalid BackendFeature, bad type '@backstage/BackendFeatureFactory'
[1]     at toInternalBackendFeature (/mnt/c/work/ASD/backstage-asd/node_modules/@backstage/backend-defaults/node_modules/@backstage/backend-app-api/src/wiring/BackendInitializer.ts:547:11)
[1]     at isServiceFactory (/mnt/c/work/ASD/backstage-asd/node_modules/@backstage/backend-defaults/node_modules/@backstage/backend-app-api/src/wiring/BackendInitializer.ts:561:20)
[1]     at BackendInitializer.#addFeature (/mnt/c/work/ASD/backstage-asd/node_modules/@backstage/backend-defaults/node_modules/@backstage/backend-app-api/src/wiring/BackendInitializer.ts:163:9)
[1]     at BackendInitializer.#doStart (/mnt/c/work/ASD/backstage-asd/node_modules/@backstage/backend-defaults/node_modules/@backstage/backend-app-api/src/wiring/BackendInitializer.ts:194:12)
[1]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[1]     at BackendInitializer.start (/mnt/c/work/ASD/backstage-asd/node_modules/@backstage/backend-defaults/node_modules/@backstage/backend-app-api/src/wiring/BackendInitializer.ts:187:5)
[1]     at BackstageBackend.start (/mnt/c/work/ASD/backstage-asd/node_modules/@backstage/backend-defaults/node_modules/@backstage/backend-app-api/src/wiring/BackstageBackend.ts:38:11)
[1] 
[1] Node.js v20.9.0

![image](https://github.com/user-attachments/assets/cfc59956-b17a-42d4-ad57-fd934b46d876)

Commenting this line, and thus not activating Microcks let backstage starts properly

### Expected behavior

Backstage should be working properly with the plugin enabled

### Microcks version or git rev

0.0.5

**Comment by lbroudoux** [comment]
I've started working on that and currently trying to reproduce it.

**Comment by lbroudoux** [comment]
Ok. Got base stuff working with the new version of the backend plugin system. Now investigating how to migrate this properly.

**Comment by Damounet** [comment]
```bash

[backend]: 2024-11-19T09:33:57.322Z catalog info Discovering ApiEntities from Microcks https://xxxxx target=MicrocksApiEntityProvider:production
[backend]: 2024-11-19T09:33:57.418Z catalog info Keycloak authentication is enabled, retrieving a OAuth token on https://xxxx/realms/microcks/protocol/openid-connect/token target=MicrocksApiEntityProvider:production
[backend]: 2024-11-19T09:33:57.696Z catalog info Adding a new microcksServer in OpenAPI specification target=MicrocksApiEntityProvider:production
[backend]: 2024-11-19T09:33:57.731Z catalog info Discovered ApiEntity Contrat d engagement - v1 target=MicrocksApiEntityProvider:production
[backend]: 2024-11-19T09:33:57.802Z catalog info Adding a new microcksServer in OpenAPI specification target=MicrocksApiEntityProvider:production
[backend]: 2024-11-19T09:33:57.849Z catalog info Discovered ApiEntity Contrat d'engagement - v1 target=MicrocksApiEntityProvider:production
[backend]: 2024-11-19T09:33:57.947Z catalog info Adding a new microcksServer in OpenAPI specification target=MicrocksApiEntityProvider:production
[backend]: 2024-11-19T09:33:57.962Z catalog info Discovered ApiEntity Data Inclusion API - 0.1.0 target=MicrocksApiEntityProvider:production
[backend]: 2024-11-19T09:33:58.059Z catalog info Adding a new microcksServer in OpenAPI specification target=MicrocksApiEntityProvider:production
[backend]: 2024-11-19T09:33:58.082Z catalog info Discovered ApiEntity Diagnostic Individus - 2.0 target=MicrocksApiEntityProvider:production
[backend]: 2024-11-19T09:33:58.186Z catalog info Adding a new microcksServer in OpenAPI specification target=MicrocksApiEntityProvider:production
[backend]: 2024-11-19T09:33:58.208Z catalog info Discovered ApiEntity Diagnostic Individus - 3.0 target=MicrocksApiEntityProvider:production
[...]
```

![image](https://github.com/user-attachments/assets/a55e72f2-3131-4216-9d08-993d7ea9164b)

It seems to work like a charm in local on my instance !
